### ISSUE TITLE
Url gets invalid if instance metadata return role arn instead of just a role name

### ISSUE THREAD

**Issue by uweje** [HENNGE/aiodynamo#61]
Hey

I found another problem while using this library.

When using `InstanceMetadataCredentials` there is an error thrown from httpx:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiodynamo/http/httpx.py", line 18, in wrapper
    return await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/aiodynamo/http/httpx.py", line 33, in get
    response = await self.client.get(str(url), headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/httpx/client.py", line 1236, in get
    return await self.request(
  File "/usr/local/lib/python3.8/site-packages/httpx/client.py", line 1086, in request
    request = self.build_request(
  File "/usr/local/lib/python3.8/site-packages/httpx/client.py", line 200, in build_request
    url = self.merge_url(url)
  File "/usr/local/lib/python3.8/site-packages/httpx/client.py", line 220, in merge_url
    url = self.base_url.join(relative_url=url)
  File "/usr/local/lib/python3.8/site-packages/httpx/models.py", line 229, in join
    return URL(relative_url)
  File "/usr/local/lib/python3.8/site-packages/httpx/models.py", line 108, in __init__
    raise InvalidURL("No host included in URL.")
httpx.exceptions.InvalidURL: No host included in URL.
```

I could track the problem down to [this line](https://github.com/HENNGE/aiodynamo/blob/edc7b3379257a6f1d6c2aca29e5617e760c9c037/src/aiodynamo/credentials.py#L310)

```python
>>> role_url = URL("http://169.254.169.254/latest/meta-data/iam/security-credentials/")
>>> role = "test-role"
>>> role_url.join(URL(role))
URL('http://169.254.169.254/latest/meta-data/iam/security-credentials/test-role')
>>> role = "arn:aws:iam::1234567890:role/test-role"
>>> role_url.join(URL(role))
URL('arn:aws:iam::1234567890:role/test-role') # expected would be URL('http://169.254.169.254/latest/meta-data/iam/security-credentials/arn:aws:iam::1234567890:role/test-role')
```

My use case is that the request gets intercepted with [KIAM](https://github.com/uswitch/kiam) and my code is supposed to assume this role. I tried the urls with curl and they worked as expected.

**Comment by ojii** [comment]
@uweje could you give my pull request a try? I don't have an easy way to test the KIAM setup myself.

**Comment by uweje** [comment]
@ojii your change is working for my setup. Thanks a lot
